application: swe-gaeshop
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: gaeshop.py

builtins:
- datastore_admin: on
- appstats: on

inbound_services:
- warmup
